# Generated by Django 4.1.4 on 2022-12-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('price', models.CharField(max_length=32)),
                ('cuisine', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
