# Generated by Django 4.1.4 on 2022-12-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0002_rename_contact_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
