# Generated by Django 4.1.4 on 2023-01-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0004_alter_restaurant_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='number',
        ),
    ]
