# Generated by Django 4.1.4 on 2023-01-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0005_remove_restaurant_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
