# Generated by Django 4.1.4 on 2023-03-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0006_restaurant_number_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='number',
            field=models.CharField(max_length=12),
        ),
    ]
