# Generated by Django 4.1.4 on 2023-01-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0008_alter_review_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
